name: hitmengame
version: '${project.version}'
main: com.ronlab.hitmengame.HitmanPlugin
api-version: '26.2'
description: Hitman companion plugin for Ronlab Game Assistant (RGA)
dependencies:
  server:
    RonlabGameAssistant:
      required: true
      join-classpath: true
